### ISSUE TITLE
Desktop App - side menu issue

### ISSUE THREAD

**Issue by meowcodes** [protoblock/protoblock#2]
Side menu is sticky when resizing window
![screen shot 2018-07-30 at 10 56 02 am](https://user-images.githubusercontent.com/29313935/43414277-2f4ece58-93e7-11e8-8969-3371031ee2d2.png)

**Comment by jaybny** [comment]
ack - the feature of the desktop app is to become a mobil app, on resize. however the light-client gui has forked off this code many moons ago. the fix would be to disable the feature by setting a min window size
